image_out_dir: null #/home/aadhithya/tactile-learning/tactile_learning/out/2023.09.05/19-19_temporal_ssl_cube_flipping_sim_view_0
image_model_type:  pretrained

tactile_out_dir: null
tactile_model_type: pretrained

vinn_image_out_dir: null
vinn_image_model_type: byol

data_path: /home/aadhithya/Holo-Bot/extracted_data/pinch_grasping_final_2

name: pinchgraspingsim
task_name: CubePinchGraspingSim-v1
camera_num: 0

expert_demo_nums: [255] # [170,171,172,173,174,175,176]
arm_offset_scale_factor: 0.03
hand_offset_scale_factor: 0.03

offset_mask: [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0]

action_type: robot