_target_: allegro_sim.agents.rewarder.penalty.ObjectDroppingPenaltySim
expert_demos: ???
image_encoder: null 
tactile_encoder: null
device: ${device}
sinkhorn_rew_scale: 1.  # This gets updated anyways

representation_types: ${reward_representations}
expert_frame_matches: ${expert_frame_matches}
episode_frame_matches: ${episode_frame_matches}